In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pymc3 as pm
import theano.tensor as tt
%matplotlib inline
plt.style.use('ggplot')

In [2]:
breaks = [10,30,70, 100]

model = pm.Model()
with model:
    x = pm.DiscreteUniform('x',0,200)
    y =  (x <= breaks[0]) * 1 + (breaks[0] < x <= breaks[1]) * 1 + (breaks[1] < x <= breaks[2]) * 1 + (breaks[2] < x <= breaks[3]) * 1
    pm.Deterministic('y',y)
    trace = pm.sample(100)

TypeError: Variables do not support boolean operations.

In [3]:
breaks = [10,30,70, 100]

model2 = pm.Model()
with model2:
    x = pm.DiscreteUniform('x',0,200)
    y =  (x <= breaks[0]) * 1 + (breaks[0] < x <= breaks[1]) * 2 + (breaks[1] < x <= breaks[2]) * 3 + (breaks[2] < x <= breaks[3]) * 4
    #pm.Deterministic('y',y)
    trace = pm.sample(100)

TypeError: Variables do not support boolean operations.

In [17]:
breaks = [1,3,7, 10]

model3 = pm.Model()
with model3:
    x = pm.DiscreteUniform('x',0,10)
    y =  (x <= breaks[2]) * 1
    z = (breaks[0] < x <= breaks[1])
    pm.Deterministic('y',y)
    trace = pm.sample(100)

TypeError: Variables do not support boolean operations.

In [15]:
trace['y']

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
       False, False,  True,  True, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False, False, False, False,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False, False], dtype=bool)

In [13]:
trace['x']

array([100, 100, 100,  99,  98,  97,  97,  97,  97,  97,  96,  97,  97,
        99, 100, 101, 101, 100, 101, 101, 101, 100,  99,  99, 100, 100,
        98,  94,  94,  94,  94,  92,  93,  93,  92,  92,  92,  94,  93,
        93,  92,  92,  93,  94,  92,  92,  92,  92,  91,  90,  90,  91,
        93,  93,  94,  94,  93,  94,  93,  92,  93,  95,  96,  95,  94,
        96,  97,  98,  98,  97,  97,  96,  95,  96,  94,  93,  93,  93,
        91,  91,  92,  91,  89,  88,  87,  87,  86,  86,  86,  86,  87,
        87,  86,  87,  86,  85,  86,  85,  86,  87], dtype=int64)

In [25]:
breaks = [10,30,70, 100]

model2 = pm.Model()
with model2:
    x = pm.DiscreteUniform('x',0,200)
    y = pm.math.gt(breaks[0] , x) + pm.math.gt(breaks[1] , x) #+ breaks[1] < x + breaks[2] < x + breaks[3] < x
    pm.Deterministic('y',y)
    trace = pm.sample(100)

100%|████████████████████████████████████████| 100/100 [00:01<00:00, 62.77it/s]


In [27]:
trace['y']

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False], dtype=bool)

In [31]:
breaks = [1,3,7, 10]

model2 = pm.Model()
with model2:
    x = pm.DiscreteUniform('x',0,10)
    y = pm.math.sgn(x - breaks[0]) + pm.math.sgn(x - breaks[1]) + pm.math.sgn(x - breaks[2]) + pm.math.sgn(x - breaks[3])
    pm.Deterministic('y',y)
    trace = pm.sample(100)

100%|██████████████████████████████████████| 100/100 [00:00<00:00, 1582.23it/s]


In [32]:
trace['y']

array([ 0, -1, -2, -2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  1,
        1,  1,  0,  0,  0,  0,  1,  2,  1,  1,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0, -1, -2, -2, -2, -2, -1, -1, -1, -2, -1,  0,
        0, -2, -3, -4, -4, -3, -3, -2, -3, -3, -3, -2, -3, -1,  0,  0,  0,
        0, -1,  0,  0,  0,  0,  0,  0,  0, -2, -2, -1,  0,  0,  0,  0, -1,
       -3, -4, -4, -4, -4, -3, -4, -4, -4, -4, -2, -2, -2, -1, -2], dtype=int64)

In [33]:
trace['x']

array([5, 3, 2, 2, 4, 4, 4, 4, 4, 4, 5, 4, 5, 6, 7, 9, 7, 7, 7, 5, 5, 5, 6,
       7, 8, 7, 7, 6, 6, 5, 4, 4, 4, 5, 5, 4, 4, 4, 4, 4, 3, 2, 2, 2, 2, 3,
       3, 3, 2, 3, 4, 4, 2, 1, 0, 0, 1, 1, 2, 1, 1, 1, 2, 1, 3, 4, 4, 4, 4,
       3, 4, 6, 5, 4, 4, 5, 4, 2, 2, 3, 4, 5, 5, 4, 3, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 2, 2, 2, 3, 2], dtype=int64)

In [43]:
breaks = [10,13,17, 20]
from pymc3.math import where,switch

model2 = pm.Model()
with model2:
    x = pm.DiscreteUniform('x',9,20)
    y = where(x < breaks[0],0, where(x < breaks[1], 1, where(x < breaks[2], 2, where( x < breaks[3], 3, 4))))
    pm.Deterministic('y',y)
    trace = pm.sample(100)

100%|██████████████████████████████████████| 100/100 [00:00<00:00, 2314.78it/s]


In [44]:
trace['y']

array([1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 3], dtype=int8)

In [49]:
def index_breaks(rv, breaks, base=0):
    # if rv <= breaks[0] return 0 else rv <= breaks[1] return 1 ...
    if len(breaks) == 2:
        return pm.math.where(rv <= breaks[0], base, base+1)
    return pm.math.where(rv <= breaks[0], base, index_breaks(rv, breaks[1:], base = base +1))

In [53]:
model2 = pm.Model()
with model2:
    x = pm.DiscreteUniform('x',9,20)
    y = index_breaks(x, breaks)
    pm.Deterministic('y',y)
    trace = pm.sample(200)

100%|██████████████████████████████████████| 200/200 [00:00<00:00, 3246.62it/s]


In [54]:
trace['x']

array([10, 10,  9, 10, 12, 12, 12, 12, 12, 13, 14, 13, 12, 12, 13, 15, 14,
       13, 13, 14, 14, 16, 17, 16, 16, 17, 16, 15, 15, 15, 14, 14, 15, 15,
       14, 15, 14, 14, 13, 12, 13, 15, 16, 15, 15, 14, 13, 14, 15, 15, 14,
       14, 14, 14, 15, 14, 13, 14, 15, 16, 16, 17, 16, 17, 17, 17, 18, 18,
       18, 20, 20, 19, 18, 19, 20, 19, 17, 17, 16, 17, 16, 13, 15, 16, 16,
       16, 14, 13, 13, 14, 14, 15, 15, 17, 18, 17, 16, 15, 16, 17, 17, 17,
       17, 17, 17, 17, 13, 13, 16, 16, 16, 16, 16, 16, 16, 20, 20, 20, 20,
       20, 15, 15, 14, 14, 12, 17, 19, 19, 13, 13, 13, 14, 15, 15, 16, 16,
       16, 16, 16, 16, 16, 20, 18, 14, 18, 18, 18, 18, 18,  9, 20, 15, 14,
       20, 20, 14, 10, 10, 10, 10, 19, 16,  9, 11, 15, 14, 19,  9,  9, 15,
       15, 15, 15, 15, 15, 15, 15, 10, 13, 19, 19, 19, 19, 13, 13, 18, 15,
       10, 10, 19, 20, 16, 10, 14, 14, 14, 13, 10, 15, 14], dtype=int64)

In [55]:
trace['y']

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 2,
       1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2,
       2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       3, 3, 3, 3, 3, 2, 2, 2, 2, 1, 2, 3, 3, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 3, 3, 2, 3, 3, 3, 3, 3, 0, 3, 2, 2, 3, 3, 2, 0, 0, 0, 0, 3,
       2, 0, 1, 2, 2, 3, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 1, 3, 3, 3, 3, 1,
       1, 3, 2, 0, 0, 3, 3, 2, 0, 2, 2, 2, 1, 0, 2, 2], dtype=int8)

In [ ]:
model2 = pm.Model()
with model2:
    x = pm.DiscreteUniform('x',0,1)
    y = 
    pm.Deterministic('y',y)
    trace = pm.sample(200)

In [ ]:
breaks = [10,30,70, 100]

model = pm.Model()
with model:
    x = pm.DiscreteUniform('x',0,200)
    y =  (x <= breaks[0]) * 1 + (breaks[0] < x <= breaks[1]) * 1 + (breaks[1] < x <= breaks[2]) * 1 + (breaks[2] < x <= breaks[3]) * 1
    pm.Deterministic('y',y)
    trace = pm.sample(100)

In [2]:
breaks = [10,30,70, 100]

model = pm.Model()
with model:
    x = pm.DiscreteUniform('x',0,200)
    y =  (x <= breaks[0]) * 1 + (breaks[0] < x <= breaks[1]) * 1 + (breaks[1] < x <= breaks[2]) * 1 + (breaks[2] < x <= breaks[3]) * 1
    pm.Deterministic('y',y)
    trace = pm.sample(100)

In [3]:
pm.DiscreteUniform?

In [8]:
%%time
model = pm.Model()
with model:
    x = pm.Normal('x', mu=np.array([10,20,30,40,50]), sd=np.array([1,1,1,1,1]), shape=5)
    trace=pm.sample(100)

100%|███████████████████████████████████████| 100/100 [00:00<00:00, 474.37it/s]


Wall time: 9.63 s


In [11]:
len(trace['x'])

100

In [12]:
trace['x'][:5]

array([[ 10.03080638,  19.15495347,  28.9598143 ,  43.19849188,
         49.89394867],
       [ 10.03080638,  19.15495347,  28.9598143 ,  43.19849188,
         49.89394867],
       [  9.53236226,  20.6865752 ,  30.80182347,  36.77101514,
         49.55314715],
       [  8.93598263,  20.57770694,  30.67960741,  37.65225738,
         50.01309196],
       [  9.94469624,  21.08008608,  29.16113617,  40.8262205 ,
         48.92310006]])

In [14]:
%%time
model = pm.Model()
with model:
    x = pm.DiscreteUniform('x', lower =np.array([10,20,30,40,50]), upper=np.array([15,25,35,45,55]), shape=5)
    trace = pm.sample(100)

100%|██████████████████████████████████████| 100/100 [00:00<00:00, 1760.54it/s]


Wall time: 20.5 s


In [16]:
trace['x'][:5]

array([[10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [11, 21, 31, 41, 50]], dtype=int64)

In [62]:
%%time
model = pm.Model()
x = np.tile(np.arange(50),(5,1))
guard = -1
with model:
    breaks = pm.DiscreteUniform('x', lower =np.array([10,20,30,40,50]), upper=np.array([15,25,35,45,55]), shape=5)
    _breaks = tt.transpose(tt.tile(breaks,(50,1)))
    logic = pm.Deterministic('logic',x > _breaks)
    mask = pm.Deterministic('mask', pm.math.where(logic, 1, 0))
    index = pm.Deterministic('index', tt.argmin(mask,0))
    #index = pm.Deterministic('index', tt.cast(logic,axis=1))
    trace = pm.sample(100)

100%|███████████████████████████████████████| 100/100 [00:00<00:00, 515.46it/s]


Wall time: 2.3 s


In [63]:
trace['logic'][0]

array([[False, False, False, False, False, False, False, False, False,
        False, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, Fal

In [64]:
trace['mask'][0]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0]], dtype=int8)

In [65]:
trace['index'][0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4,
       4, 4, 4, 4], dtype=int64)

In [66]:
%%time
model = pm.Model()
x = np.tile(np.arange(50),(5,1))
with model:
    breaks = pm.DiscreteUniform('x', lower =np.array([10,20,30,40,50]), upper=np.array([15,25,35,45,55]), shape=5)
    _breaks = tt.transpose(tt.tile(breaks,(50,1)))
    logic = pm.Deterministic('logic',x > _breaks)
    mask = pm.Deterministic('mask', pm.math.where(logic, 1, 0))
    index = pm.Deterministic('index', tt.sum(mask,0))
    #index = pm.Deterministic('index', tt.cast(logic,axis=1))
    trace = pm.sample(100)

100%|████████████████████████████████████████| 100/100 [00:01<00:00, 56.75it/s]


Wall time: 3.24 s


In [67]:
trace['index'][0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4,
       4, 4, 4, 4], dtype=int64)

In [68]:
np.array([1,2,3])[[1,0,1,0]]

array([2, 1, 2, 1])

In [69]:
X = np.arange(4*4).reshape((4,4))

In [70]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [71]:
X[[1,2,1,2,1,2]]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
X[[[1,2],[1,2],[1,2]]]

IndexError: too many indices for array

In [74]:
X[[1,2],[1,2],[1,2]]

IndexError: too many indices for array

In [75]:
X[[1,2,1,2,1,2]]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
X.take?

In [77]:
np.take?

In [78]:
np.take(X,[1,2,3])

array([1, 2, 3])

In [79]:
X[[1,2,3]]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [82]:
np.take(X,[[1,2],[1,2]],axis=(1,2))

TypeError: an integer is required for the axis

In [83]:
Y=np.tile(X,(3,1,1))

In [84]:
Y[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [85]:
Y[1]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [86]:
np.stack([X,X]).shape

(2, 4, 4)

In [2]:
pm.sample?